# Generated by Django 5.0.6 on 2024-06-07 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 6, 7, 22, 22, 19, 848837, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Uploaded At",
            ),
            preserve_default=False,
        ),
    ]
